version: "3.8"

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scanner
    volumes:
      - .:/app
    command: ["python", "main.py"]
    ports:
      - "5000:5000"  
    env_file:
      - .env 